language: node_js

node_js: "8"

addons:
  chrome: stable

install:
  - npm install
  - npm install -g codecov

cache: npm

script:
  - xvfb-run npm test
  - codecov

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: "build/es6-bundled/demo"
  on:
    branch: master
