language: node_js

node_js: "8"

addons:
  chrome: stable

install:
  - npm install
  - npm install -g codecov

script:
  - npm test
  - codecov
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: "build/es6-bundled/demo"
  on:
    branch: master
