language: node_js

node_js: "8"

addons:
  chrome: stable

install:
  - npm install
  - npm install -g codecov

cache: npm

script:
  - npm test
  - codecov
  - npm run build

deploy:
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: "build/es6-bundled/demo"
    on:
      tags: true

  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_AUTH_TOKEN
    on:
      tags: true
