version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build demo
          command: npm run build
