version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    environment:
      - SOURCE_BRANCH: feature/ci
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - deploy:
          name: Deploy to gh-pages
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_NAME

              git clone $CIRCLE_REPOSITORY_URL out

              cd out
              git checkout $SOURCE_BRANCH || git checkout --orphan $TARGET_BRANCH
              git rm -rf .
              cd ..

              npm run build

              cp -a build/es6-bundled/demo/. out/.

              cd out

              git add -A
              git commit -m 'deploy to Github Pages' --allow-empty
              git push origin $TARGET_BRANCH
            fi
