version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    environment:
      - SOURCE_BRANCH: feature/ci
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
      - add_ssh_keys:
          fingerprints:
            - "d4:b0:fd:6b:48:44:97:d2:34:82:c5:f2:c0:74:03:66"
      - deploy:
          name: Deploy to gh-pages
          command: ./deploy.sh
